export socket, { idReducer as id } from 'cape-redux-socket'
export { fieldReducer as form } from 'redux-field'
export { historyReducer as history } from 'redux-history-sync'

export auth from './auth'
export db from './modules/db'
export entity from './modules/entity'
export errorMessage from './modules/errorMessage'
export mixer from './modules/mixer'
export triple from './triple'
